# Global constants for database columns
USER_INDEX_COLUMN    = 0
USER_API_KEY_COLUMN  = 1
USER_USERNAME_COLUMN = 2
USER_PASSWORD_COLUMN = 3
USER_EMAIL_COLUMN    = 4
USER_DISPLAY_COLUMN  = 5
USER_ACTIVE_COLUMN   = 6
USER_ADMIN_COLUMN    = 7
USER_PW_RESET_COLUMN = 8

PLAYER_ROUND_ID_COLUMN      = 0
PLAYER_USER_ID_COLUMN       = 1
PLAYER_TABLE_ID_COLUMN      = 2
PLAYER_INITIAL_STACK_COLUMN = 3
PLAYER_STACK_COLUMN         = 4
PLAYER_MY_TURN_COLUMN       = 5
PLAYER_HAND1_COLUMN         = 6
PLAYER_HAND2_COLUMN         = 7
PLAYER_IS_FOLDED_COLUMN     = 8
PLAYER_DISPLAY_COLUMN       = 9

TABLE_INDEX_COLUMN          = 0
TABLE_ROUND_COLUMN          = 1
TABLE_CURRENT_BET_COLUMN    = 2
TABLE_CURRENT_POT_COLUMN    = 3
TABLE_PHASE_COLUMN          = 4
TABLE_COMM1_COLUMN          = 5
TABLE_COMM2_COLUMN          = 6
TABLE_COMM3_COLUMN          = 7
TABLE_COMM4_COLUMN          = 8
TABLE_COMM5_COLUMN          = 9
