# Global constants for database columns
USER_INDEX_COLUMN    = 0
USER_API_KEY_COLUMN  = 1
USER_USERNAME_COLUMN = 2
USER_PASSWORD_COLUMN = 3
USER_EMAIL_COLUMN    = 4
USER_DISPLAY_COLUMN  = 5
USER_ACTIVE_COLUMN   = 6
USER_ADMIN_COLUMN    = 7
USER_PW_RESET_COLUMN = 8
